### ISSUE TITLE
getting this error when deploy it on real device with android 5.1

### ISSUE THREAD

**Issue by A-bahattab** [strider-/BankLedger#1]
when I build app there is no error and seems working fine. but when i deploy it on a real device with android 5.1 samsung its just field to deploy and show this error:
 
Error		ADB0000:  Deployment failed
Mono.AndroidTools.InstallFailedException: Unexpected install output: 	pkg: /data/local/tmp/com.strider.bankledger-Signed.apk
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName)
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()			 	0	Build	
--------------------------------------------------------------
--------------------------------------------------------------
_But its working fine on emulator with android 9.0_

**Comment by strider-** [comment]
Not sure how much help I can be as I don't have any devices running 5.1, but I'll try my best.  Can you paste or attach the generated `AndroidManifest.xml` file?  It should be located in your project directory under `\BankLedger.Android\obj\$(Configuration)\$(Version)\android`.
